name: gasv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - matplotlib
  - netcdf4
  - jplephem
  - pyinstaller
  - cartopy
prefix: /home/GeoAS/Software/miniconda3/envs/gasv